### ISSUE TITLE
Duplicate card issue 

### ISSUE THREAD

**Issue by sreerajlal** [stripe/sca-dev-chats#16]
when ever i Start a subscription with a trial same card saving multiple times 

## API
SetupIntents

## Stripe Products
Billing

## Tech stack
PHP, React,2019-05-16,Stripe/v1

<img width="1120" alt="Screenshot 2019-09-06 at 3 46 52 PM" src="https://user-images.githubusercontent.com/32412719/64420754-95ac3c80-d0bd-11e9-90c6-455ee28e0db0.png">

**Comment by tbell511** [comment]
Hi @sreerajlal, I recommend adding code snippets so the Stripe devs can take a look at what you're doing. Might save you some time if you're able to do that before they take a look.

**Comment by thorsten-stripe** [comment]
@sreerajlal I'm afraid, as Tyler mentioned, I'd need more details about your integration. It sounds like it might be similar to https://github.com/stripe/stripe-payments-demo/issues/45 so maybe see if you find a resolution there. Otherwise, please use our normal support channels ( https://support.stripe.com/email ) as this doesn't sound SCA related.
