### ISSUE TITLE
When to use automatic confirmation?

### ISSUE THREAD

**Issue by soju7** [stripe/sca-dev-chats#8]
## Topic

I read the stripe documentation for SCA pretty neatly. i have a little bit trouble understanding when to use `automatic confirmation` and when to use `manual confirmation` [https://stripe.com/docs/payments/payment-intents/quickstart#automatic-confirmation-flow](url) .
step 5 states that
 `your integration should not attempt to handle order fulfillment on the client side because it is possible for customers to leave the page after payment is complete but before the fulfillment process initiates. Instead, you will need to handle asynchronous events in order to be notified and drive fulfillment when the payment succeeds.`
How should customer leave the page before fulfillment?because the client side code have full control over it and it can prevent user from leaving the page.correct me if i was wrong
## API

What API does your question relate to: <|PaymentIntents|>

## Stripe Products

What Stripe Products are you using: <|Billing|>

## Tech stack

- Backend language/frameworks: <|PHP|>
- Frontend libraries/frameworks: <|Vue|>

**Comment by mikeshaw-stripe** [comment]
Hi @soju7,

Because in Automatic confirmation you are confirming the PaymentIntent this moves money between your Customer and your Stripe Account. When the Promise resolves on your frontend you are not guaranteed that the customer is still there. Their device could have disconnected due to connectivity issues of loss of power etc. 

That is why we recommended asynchronously checking with stripe either via webhooks (push) or a poll (pull) on your backend. 

If you are comfortable building support for asynchronous payments we would recommend using Automatic confirmation as there are already a lot of payment methods worldwide that settle asynchronously and with cards now moving to 3D Secure it's becoming more relevant. 

Hope this helps! 

Mike
